apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  selector:
    matchLabels:
      app: nodejs
      version: "1.0"
  template:
    metadata:
      labels:
        app: nodejs
        version: "1.0"
    spec:
      containers:
      -  image: amanpreet9391/simple-nodejs-app:f252e0a
         imagePullPolicy: Always
         name: nodejs-app-blue
         ports:
         -  name: nodejs-port
            containerPort: 3000
              