apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    app: nodejs
    version: "1.1"  # Pointing towards green-deployment
  type: LoadBalancer
  ports:
  -  targetPort: 3000
     port: 3000
     




