apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
    version: "1.0"  # Pointing towards blue-deployment
  type: LoadBalancer
  ports:
  -  targetPort: 3000
     port: 3000
     




