apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
    version: "1.0"  # service is pointing towards blue deployment
  type: NodePort
  ports:
  -  targetPort: 3000
     port: 3000
     nodePort: 30008